# Generated by Django 4.2.14 on 2024-07-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_direction",
                    models.CharField(max_length=100, verbose_name="наименование"),
                ),
                ("description", models.TextField(verbose_name="описание направления")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_service",
                    models.CharField(max_length=250, verbose_name="наименование"),
                ),
                ("description", models.TextField(verbose_name="описание")),
                ("price", models.IntegerField(verbose_name="стоимость")),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostic_center.direction",
                        verbose_name="направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="person/", verbose_name="фото"
                    ),
                ),
                (
                    "direction",
                    models.ManyToManyField(
                        related_name="direction",
                        to="diagnostic_center.direction",
                        verbose_name="направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "врач",
                "verbose_name_plural": "врачи",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="дата и время приема")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="записи",
                        to="diagnostic_center.doctor",
                        verbose_name="врач",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="записи",
                        to="diagnostic_center.service",
                        verbose_name="услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись на диагностику",
                "verbose_name_plural": "записи на диагностику",
            },
        ),
    ]
