# Generated by Django 4.2.14 on 2024-07-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostic_center", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="direction",
        ),
        migrations.AddField(
            model_name="doctor",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diagnostic_center.direction",
                verbose_name="направление",
            ),
        ),
    ]
