# Generated by Django 4.2.14 on 2024-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostic_center", "0004_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, null=True, verbose_name="артикул"),
        ),
    ]
